title: F-Flat
baseurl: "/f-flat_node" # the subpath of your site, e.g. /blog
url: "https://hypercubed.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hypercubed
github_username:  hypercubed
show_downloads: false

# Build settings
theme: jekyll-theme-midnight

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
